title: OpendDrive Documentation
description: OpenDrive Framework is an open-source project designed to accelerate the development of autonomous driving systems.
theme: just-the-docs

url: https://OpenDriveDevelopment.github.io/OpenDrive-Documentation

aux_links:
  Template Repository: https://OpenDriveDevelopment.github.io/OpenDrive-Documentation
