title: OpendDrive Documentation
description: OpenDrive Framework is an open-source project designed to accelerate the development of autonomous driving systems.
theme: just-the-docs

url: https://OpenDriveDevelopment.github.io/OpenDrive-Documentation

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/FullLogoOpenDrive.png"

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

aux_links:
  View on Github: https://OpenDriveDevelopment.github.io/OpenDrive-Documentation
  
